version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://qwerty:Qwerty123!@db:5432/majestic_sapp
      - REDIS_URL=redis://redis:6379/0
      - FORWARDED_ALLOW_IPS=*
      - PROXY_HEADERS=true 
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: qwerty
      POSTGRES_PASSWORD: Qwerty123!
      POSTGRES_DB: majestic_sapp
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  db_data: